language: node_js
sudo: false
node_js:
- 4
- 6
script:
- npm run ci
# - sonar-scannergit 
- chmod 777 ./test/shell_scripts/run_tests.sh
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: yCb6Fq7irouCMHWlThDyFYD6y5oSbik+esS0CICrI+cuPZmVC9gO+A5h4GbfT0Q+TV8qpRqo+Y5eVQsneozgIjlXCBaG3FatHByH6Gv2XnxhPRRbz5ynCAwCTMMzJGAdZIbVNS7V9CHLqrXGQHMobupXwgOieOGr08mOVaUDrg0vctaD83OY+bmfYCTJZ4ngQrsnlkyepUSqaNEK2z70CaAK3JG1H4XX8/vSSLSXCxwK5Di6hfi373qC0WG56RqLJUTcDEmT5YmOp1d9WPwPSHahfCWSOwo9zbXKoAM9euptrCA6c0p/argoV4PSSYehHv0ZEycnt+tbJxI3UfIaHNVxr9gVDuGBsxJi3GBifqlbdIpgkCrfFPpzvVzNk9kF4b6SAdKKHjD9IhTLkVtSAyMr1lSSX1muU4nZ+q8d3wG+yZt881EOYxCNMEMnwYp8nsNjGbrMw4CU1vDlD1vly3C+JihoAdQfm9rH/Onyy91uoYwB1OJnGbfYUPic89k7gtVgw79fhRtd18DdQMK43Iwne42Z/ue5KLgvBE1Wi0lKhMYeI2uIl66Y2ZHalTIEZyurSXohVejHnDs6f9M+Aw6CIajcPNl+/imS/SinTJN7RrRafAVsiqWBUktvDcL5rwDRFJNqtsM+0RuZAmsdE/No25s/4fo9UK/VHYb7n20=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: o3fw+zSFJMnmM1c2kJJ4zXlPTYO6Zhr4jeQpXKYDhwatO7PC15IyRv7lfCRvVgrPAZqxE2RRc7+0xd/FEpkO8SI+1U6WD/ZD4MIa7TlcrnTqN3hyLL0Pxu1koZVk9rTohCAcnp1tQek5xUIKO5H7VfhHRA5l4rPYnWyotV/oYciYnUpOd7/ZwZYkAYMDd/3uhI04q/gV0P+xQCPImUbkU/HwOE/drBdq3j1sWO6QjkwPN2F94+o1HJs9maixz2Z/miZamjT2xX4aoP8//dqRWA+2Dji4Jj7y7biVdV9iHljnPV4ycXhSs1DmnMICpS0QD/7mRshaYJPXRgIqIxwCyWtyoQhsw7KU6tGUWDp/Ys8v4NXcCgZotv62KrcgXfbxGtlteOvdB9dNKvJFeEQd2x09z4p1AQRseRkjEZ1Ua8JJMzFuaCawHLtk9Ouu5o4TONtDPjt2f/n7xukDSeDZDVjNYNuDIApUbRC+LdqIMOa7RTKnNcYSly6qW27e3HDvIHOqV0Vx3ar1x+zXpz7YUR7KpiFrj5QyCKjisT+ZoruAHlNnkM/1+SblPEJci8UR+Vu/mdI07MTVo/CwAfrCMl9V8hX2lcNuUyqGYsZM9VPbgg80d21t3HuUOr3j1pyf7fQxSPSNZsF9bG3gqun1g/KjaEgvceumz/2jqTCVb/E=
addons:
  sonarqube:
    organization: ''
    token:
      secure: sWHEElq3q9Nv+u8SrEN5sqpyPC9+PmxXjMzjbByW13e4oMJ9aQd/KtrVz4xU7QjeNK9Jkx5hHHE6dT88q6JSg2Jfwo09dX8EwLsu/KYDqFkGEI3f0uWWWVBdNeTxcexOzdQb44GomAljTLvp7tsorS1kgWHtRhq0y4fXNIjG3eqWQJsgNoUzjEaM5fGAQmWx8FHgL+cFeIcomRpmwv0gCFKcrxSPlaZgysNBriVwHebzubmpChdr25Cr5/fJbpA699o8OBUti4L6b7dwsf2WlS2jH/0J5AQ2Cu5oDaJzajsBqHAYqcoIwcfxNpYOkIKiL4lHHWNdIEywmvAygvl2TCLORIvGUcZB2W8n1cC7p/62zFwFfxkLxdjQxEPDExNErWjrznSyUY/D+qy0QU9afLAGAPZ5bgIEa+Qd7osChDfjRGMRtfFAY4vJNKlxHu5SHg0L0GVqWkd5rn4Lv7pPHlyWXmBdiN84za52l4EKw5gA84FCInxJBvb4+4TVc+BFz/joPNuAEnDwZeRf2teVs92oMm7Uk+27aJ48sadk7ky/Nc+67qnCqrAjnZEoPUlDIy7s58SDwHHbq3x/ST5mY0uWRux6NRaMWzdRfOw/mx0BHkNjWOGnzsy6PhrnhOxJ7MFg7p2i+N+FXbaX2c1R3CcMe2QcNFfLncvXSXQNeW4=
